### ISSUE TITLE
Processing errors

### ISSUE THREAD

**Issue by EvolDoc** [degregory/SAM_Refiner#1]
Greetings,
I have encountered errors at the end of each of my analyses. Any suggestions?

Starting SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 processing
At read 5000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 5000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 10000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 10000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 15000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 15000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 20000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 20000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 25000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 25000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 30000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 30000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 35000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 35000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 40000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 40000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 45000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 45000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 50000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 50000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 55000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 55000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 60000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 60000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 65000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 65000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 70000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 70000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 75000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 75000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 80000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 80000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 85000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 85000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 90000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 90000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
At read 95000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
At line 95000 of SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50 SAM
End SAM parse for SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
End unqiue seq out for SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
End indel out for SARSCT-WastewaterxxSechristxxSWIFTxxNAUxx20210414-xx-xx-xxx-xxxx-169-CH_S50
Process Process-4:
Traceback (most recent call last):
  File "/packages/anaconda3/2020.11/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/packages/anaconda3/2020.11/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/cmh574/software/Sam_Refiner.py", line 820, in SAMparse
    AAinfo = singletCodon(POS, ref[1][POS-1], ref)
  File "/scratch/cmh574/software/Sam_Refiner.py", line 408, in singletCodon
    codon = nt+ref[1][ntPOS]+ref[1][ntPOS+1]
IndexError: string index out of range

**Comment by degregory** [comment]
I've put in what might be a quick fix if you want to try again.  If it doesn't work, if you'd be willing to share the reference and one of the sam files you are using I'll work on troubleshooting.

**Comment by EvolDoc** [comment]
Definitely :-) I'll try right now.

**Comment by EvolDoc** [comment]
Its working!! Thanks so much!
