### ISSUE TITLE
No Covariances files found

### ISSUE THREAD

**Issue by kayobianco** [degregory/SAM_Refiner#4]
Hello everyone,
I am running the command SAM_Refiner -r Spike-Wuhan-Hu-1.fasta -S sam_file, the indel, nt_call, and covars files are created, but the Collected_Covariances.tsv and Collected_Unique_Seqs.tsv files are not generated, and I receive the following message:
No Covariances files found
No Unique_Seqs files found
No Covar_Deconv files found
No Covar_Pass files found
No Chimeras_Removed files found

Can you help me?

**Comment by degregory** [comment]
Is the sam_file you are pointing to, and the outputs from processing it, in the directory where you are calling SAM_Refiner?  The collection part of the program only looks for the sample files in the current working directory.

**Comment by kayobianco** [comment]
Yes, the SAM files are in a directory called 3.SAM_Refiner.
![Captura de tela de 2023-07-12 10-24-47](https://github.com/degregory/SAM_Refiner/assets/29949536/9feca02b-6c21-4c81-8c2e-3cec588edcf1)

**Comment by degregory** [comment]
To make sure, when you point to the sam files you don't use their path?  Just '-S 27_3-23RBDA_....fastq.sam', for example?  If you are, what version of SAM_Refiner are you using?  The one currently up on github? Or an earlier version?

**Comment by kayobianco** [comment]
Carrying out the test as you suggested, the Collected files are generated, only the Covar_Pass file is not found.
"No Covar_Pass files found"

I'm using version 1.4, available in the conda repository

**Comment by degregory** [comment]
covar pass files aren't generated unless specified in the command line arguments.  It appears to be working as intended.
