### ISSUE TITLE
Amino acid fasta file

### ISSUE THREAD

**Issue by kayobianco** [degregory/SAM_Refiner#5]
Hello,
Is it possible to save the fasta file of amino acid sequences annotated as Sc2?

Best regards, Kayo

**Comment by degregory** [comment]
Could you clarify what you are asking?  SAM Refiner uses SAM files as input and outputs tsv files.  Any fasta files would be upstream and would be nucleotide sequences, not amino acid.  What is Sc2 in this context?

**Comment by kayobianco** [comment]
Dear degregory,
Sorry if my question wasn't clear.

Can SAM_refiner save fasta file of nucleotides paired with SARS-CoV-2 (Sc2) reference sequence?

**Comment by degregory** [comment]
I think I understand what you are wanting.  It won't output a fasta, but if you have it output the read tsv ( --read 1 ), it will preserve the labels from the fasta/fastq you are processing, making it easier to link the SAM Refiner output with the nt sequence.  Hope that will let you get to what you want.
